version: 2

builds:
  - id: flashdb
    dir: server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    binary: flashdb

archives:
  - id: default
    format: tar.gz
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: arindam923
    name: fastdb
  draft: false
  prerelease: auto
